name: GitHub Actions Demo
on: push
jobs: 
  Example-Actions-Job:
    name: Exploring GitHub Actions
    runs-on: ubuntu-latest
    steps:
      # Display the event that triggered the workflow
      - run: echo "Tha job was triggerted by a ${{ github.event_name }} event."

      # Display the Runner info
      - run: echo "this job is now running on a ${{ runner.os }} server hosted by GitHub"

      # Info about the repository and branch
      - run: echo "the name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
  
      # Use Action located in https://github/actions
      - name: Check out repository code
        uses: actions/checkout@v2

      - run: echo "The ${{ github.repository }} repository has heen cloned to the runner."

      - run: echo "your repository has been copied to the path ${{ github.workspace }} on the runner."

      - run: echo "The workflow is now ready to test your code on the runner."

      - name: conditional step when event name is pull request
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "This even is a pull request"

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Setup dotnet on runner
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: '8.x'

      - name: Display dotnet version 
        run: dotnet --version

      - run: echo "The preistalled tools are located here on the runner ${{ runner.tool_cache }}

      - name: List files in tool cache
        run: |
          ls ${{ runner.tool_cach }}
      - run: echo "this job's status is ${{ job.satus }}."
      
